feat: claimRequireBalance fetched from contract
nation3/citizen-app pull request #247
Opened 2024-04-08 12:17 UTC by TTNguyenDev

![image](https://github.com/nation3/citizen-app/assets/42999269/816cd382-3ae4-4448-be94-3097735e987d)
![image](https://github.com/nation3/citizen-app/assets/42999269/d783e835-0f56-4ce9-aae9-73cfaa2c3276)

2024-04-08 15:09 UTC, aahna-ashina requested changes
The [preview deployment](https://citizen-app-mainnet-git-feat-claimrequiredbalance-nation3dao.vercel.app/join) shows 0 instead of 3:

> ![image](https://github.com/nation3/citizen-app/assets/95955389/bcf42a7c-eaa4-4d1f-9ff0-24113bd7651c)

2024-04-08 15:19 UTC, TTNguyenDev commented
It worked on Sepolia, something is wrong on mainnet. I'm checking

2024-04-08 15:22 UTC, TTNguyenDev commented
![image](https://github.com/nation3/citizen-app/assets/42999269/9dd716ca-92bf-4b16-8a6f-71a6af6add69)
@aahna-ashina please check the site again

2024-04-08 15:58 UTC, TTNguyenDev commented
@aahna-ashina hi please check this 
![image](https://github.com/nation3/citizen-app/assets/42999269/6a76cf35-dbc8-41a9-bd58-ad82985ce788)

2024-04-08 16:01 UTC, TTNguyenDev commented
![image](https://github.com/nation3/citizen-app/assets/42999269/6e8d7d75-0917-4e4d-8325-ab5cd007cb1e)
This one is weird to, since we choose sepolia, but chain id = 1, can you provide me your environments?

2024-04-08 16:03 UTC, TTNguyenDev commented
Could you provide .env file on vercel

2024-04-08 16:08 UTC, TTNguyenDev commented
```
========= NOTICE =========
_app-eec73d473f391b30.js:1 Request-Rate Exceeded  (this message will not be repeated)
_app-eec73d473f391b30.js:1 
_app-eec73d473f391b30.js:1 The default API keys for each service are provided as a highly-throttled,
_app-eec73d473f391b30.js:1 community resource for low-traffic projects and early prototyping.
_app-eec73d473f391b30.js:1 
_app-eec73d473f391b30.js:1 While your application will continue to function, we highly recommended
_app-eec73d473f391b30.js:1 signing up for your own API keys to improve performance, increase your
_app-eec73d473f391b30.js:1 request rate/limit and enable other perks, such as metrics and advanced APIs.

```

The problem is from your Alchemy API, I believe

2024-04-08 16:35 UTC, TTNguyenDev commented
![image](https://github.co@aahna-ashina nation3/citizen-app/assets/42999269/868fce4e-33f4-485c-9f8f-0c3929f1c365)
@aahna-ashina some problems with user .env on vercel.
I open mainnet vercel site, but receive this message `Provider: Connected to the user's provider on chain with ID`. This message only appear if we run local node
![image](https://github.com/nation3/citizen-app/assets/42999269/335add92-879d-4e03-9434-36436b3aba00)

2024-04-14 13:07 UTC, TTNguyenDev commented
Use these new envs:
ALCHEMY_ID for mainnet: _lfSphd2SZQl-K3vAmW0pY9keqf9XDaB
ALCHEMY_ID for sepolia: GsbBvVaHjYdYuwkKn5_GTsMxbKvP8_QZ
@aahna-ashina

2024-04-14 13:44 UTC, aahna-ashina commented
> Use these new envs: ALCHEMY_ID for mainnet: _lfSphd2SZQl-K3vAmW0pY9keqf9XDaB ALCHEMY_ID for sepolia: GsbBvVaHjYdYuwkKn5_GTsMxbKvP8_QZ @aahna-ashina

@TTNguyenDev Do you mean `NEXT_PUBLIC_ALCHEMY_ID`?

2024-04-14 14:00 UTC, TTNguyenDev commented
yes

2024-04-15 06:00 UTC, aahna-ashina commented
> yes 

@TTNguyenDev Okay, updated both ✅

Did it solve the problem?

2024-04-15 06:58 UTC, TTNguyenDev commented
it should work, please check! @aahna-ashina

2024-04-16 05:51 UTC, TTNguyenDev commented
@aahna-ashina Can you help me to preview this PR, it worked on my side

2024-04-20 10:48 UTC, aahna-ashina commented on yarn.lock
> +# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
Is this lock file needed?

2024-04-20 10:51 UTC, aahna-ashina approved these changes

2024-04-20 10:55 UTC, merged