Reinstate Liquidity Rewards Program
nation3/citizen-app pull request #260
Opened 2024-05-01 12:19 UTC by hhio618

This will revert the changes made in commit https://github.com/nation3/citizen-app/commit/0d32b32d14abfb641907c30a2828cdd30c3794ef#diff-c929e9424c96a55187bf3c7ecec95438b67f7a6f20df177e368728ba4bbe4890

## Related GitHub Issue

#225

## Screenshots (if appropriate):

![liquidity](https://github.com/nation3/citizen-app/assets/1272158/be68a472-3c57-4449-88a0-a9fea5d9eb0d)

## How Has This Been Tested?

- [X] Status checks pass (lint, build, test)
- [X] Works on Sepolia preview deployment
- [ ] Works on Mainnet preview deployment

## Are There Admin Tasks?

2024-05-01 12:37 UTC, aahna-ashina requested changes
@hhio618 I tested on the Mainnet preview:  https://citizen-app-mainnet-git-fork-hhio618-main-nation3dao.vercel.app

On the `/lock` page, my $veNATION balance shows as 19.65:

> ![image](https://github.com/nation3/citizen-app/assets/95955389/b898662f-2ab5-456b-87e5-459e1ab7a899)

But on the `/liquidity` page it shows as 0:

> ![liquidity](https://github.com/nation3/citizen-app/assets/95955389/532fbc84-fa4e-4ed1-a4d2-aba7df2fac86)

Any idea why the $veNATION balance is not loading?

2024-05-01 13:48 UTC, hhio618 commented
Please test using the latest commit.

2024-05-01 17:30 UTC, aahna-ashina requested changes

2024-05-01 17:30 UTC, aahna-ashina commented on ui/pages/liquidity.tsx
> +            href={`${balancerDomain}/#/pool/${balancerPoolId}`}
```suggestion
            href={`${balancerDomain}/pool/${balancerPoolId}`}
```

2024-05-01 17:33 UTC, aahna-ashina commented
@hhio618 I'm getting a `division-by-zero` error at https://citizen-app-sepolia-i57i145rj-nation3dao.vercel.app/liquidity

Is that because of the Reward APY being zero?

> ![](https://github.com/nation3/citizen-app/assets/95955389/53c34b48-6e60-4759-9422-874654405e29)

2024-05-01 19:55 UTC, hhio618 commented
@aahna-ashina I'm not sure! Please send me the testnet token so that I can test this further.
My eth address: 0x6321286F9B73f427C72e1f9F1bC6b3d25eF06605

2024-05-02 04:06 UTC, aahna-ashina commented
> Please send me the testnet token so that I can test this further.

@hhio618 Here is how to get testnet tokens:  https://github.com/nation3/.github/blob/main/CONTRIBUTING.md

2024-05-02 08:41 UTC, hhio618 commented
@aahna-ashina Found the issue, the totalDeposit is zero in this contract: https://sepolia.etherscan.io/address/0x5514cF24D2241Ecc6012306927eA8d74E052416D#readContract. This value is being used for division in this code: https://github.com/nation3/citizen-app/blob/833fc2215aea6fa42afda8d76c6b9d63b1faee21/ui/lib/liquidity-rewards.ts#L75.

2024-05-03 05:22 UTC, aahna-ashina commented
> Found the issue, the totalDeposit is zero in this contract: https://sepolia.etherscan.io/address/0x5514cF24D2241Ecc6012306927eA8d74E052416D#readContract. This value is being used for division in this code: https://github.com/nation3/citizen-app/blob/833fc2215aea6fa42afda8d76c6b9d63b1faee21/ui/lib/liquidity-rewards.ts#L75.

@hhio618 Okay, thank you.  So if we make a deposit, the error message should disappear?

2024-05-03 05:37 UTC, hhio618 commented
@aahna-ashina You're welcome! Yes, Just add tokens using the `deposit` method, which will do the trick!

2024-05-11 06:52 UTC, aahna-ashina approved these changes

2024-05-11 06:52 UTC, merged