Fix the withdrawal contract call
nation3/citizen-app pull request #281
Opened 2024-06-04 08:12 UTC by hhio618

Fix the withdrawal contract call

## Related GitHub Issue

#279 

## Screenshots (if appropriate):

![withdraw](https://github.com/nation3/citizen-app/assets/1272158/0d071384-9b82-4d9a-8e2a-2a7e22348d2d)

## How Has This Been Tested?

- [X] Status checks pass (lint, build, test)
- [X] Works on Sepolia preview deployment
- [ ] Works on Mainnet preview deployment

## Are There Admin Tasks?

2024-06-04 08:45 UTC, aahna-ashina requested changes
@hhio618 The "Withdraw" button should not appear if the lock expiration date is _after_ the current date.

https://citizen-app-mainnet-4z9nkw531-nation3dao.vercel.app/lock
> ![](https://github.com/nation3/citizen-app/assets/95955389/b13fda2c-c437-4b43-8fa9-eaa054967ade)

2024-06-05 06:24 UTC, aahna-ashina reviewed
Tested, and it worked 👍: https://etherscan.io/tx/0x257761756ebb9bd0eff6d5ae5abb123a0618ed2b83d852cbc65689399f403a20

The hardcoded gas limit is set to 800,000.  Can you change it to 480,000?

https://github.com/nation3/citizen-app/blob/main/ui/lib/ve-token.ts#L25

2024-06-05 11:57 UTC, hhio618 commented
@aahna-ashina done!

2024-06-05 12:05 UTC, aahna-ashina approved these changes

2024-06-05 12:08 UTC, merged